#! /usr/bin/env node

const packages = require('./dependent-packages.json');
const { join } = require('path');
const { writeFileSync } = require('fs');
const { execSync } = require('child_process');

const version = process.argv[2];

if (!version) {
  console.error('Missing required version parameter');
  process.exit(1);
}

packages.forEach(p => {
  console.log(`Publishing ${p}@${version}`);

  const cwd = join(__dirname, `../packages/${p}`);
  const pkgJson = join(cwd, 'package.json');
  const pkg = require(pkgJson);
  const upgradedDeps = [];

  Object
    .keys(pkg.dependencies)
    .forEach(dep => {
      if (!dep.includes('neutrino-')) {
        return;
      }

      pkg.dependencies[dep] = `^${version}`;
      upgradedDeps.push(dep);
    });

  writeFileSync(pkgJson, `${JSON.stringify(pkg, null, 2)}\n`, { encoding: 'utf8' });
  execSync(`yarn upgrade ${upgradedDeps.join(' ')}`, { cwd });
  execSync(`npm publish`, { cwd });
  // console.log(`  yarn upgrade ${upgradedDeps.join(' ')}`);
});

